spring:
  application:
    name: service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost/mydatabase
    username: myuser
    password: secret
  modulith:
    republish-outstanding-events-on-restart: true
    events:
      jdbc:
        schema-initialization:
          enabled: true
  ai:
    openai:
      api-key: api_key
